/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query'
import type {
  GetAccommodations200,
  GetAccommodations403,
  GetAccommodationsParams
} from '../../model'
import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * @summary ログイン中のユーザーに紐づく全ての予約した宿泊施設の取得(ページネーションもあり)
 */
export const getAccommodations = (
    params: GetAccommodationsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetAccommodations200>(
      {url: `/api/accommodations`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetAccommodationsQueryKey = (params: GetAccommodationsParams,) => {
    return [`/api/accommodations`, ...(params ? [params]: [])] as const;
    }

    
export const getGetAccommodationsQueryOptions = <TData = Awaited<ReturnType<typeof getAccommodations>>, TError = ErrorType<GetAccommodations403>>(params: GetAccommodationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccommodations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAccommodationsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccommodations>>> = ({ signal }) => getAccommodations(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAccommodations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAccommodationsQueryResult = NonNullable<Awaited<ReturnType<typeof getAccommodations>>>
export type GetAccommodationsQueryError = ErrorType<GetAccommodations403>


export function useGetAccommodations<TData = Awaited<ReturnType<typeof getAccommodations>>, TError = ErrorType<GetAccommodations403>>(
 params: GetAccommodationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccommodations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccommodations>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAccommodations<TData = Awaited<ReturnType<typeof getAccommodations>>, TError = ErrorType<GetAccommodations403>>(
 params: GetAccommodationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccommodations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccommodations>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAccommodations<TData = Awaited<ReturnType<typeof getAccommodations>>, TError = ErrorType<GetAccommodations403>>(
 params: GetAccommodationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccommodations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary ログイン中のユーザーに紐づく全ての予約した宿泊施設の取得(ページネーションもあり)
 */

export function useGetAccommodations<TData = Awaited<ReturnType<typeof getAccommodations>>, TError = ErrorType<GetAccommodations403>>(
 params: GetAccommodationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccommodations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAccommodationsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetAccommodationsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getAccommodations>>, TError = ErrorType<GetAccommodations403>>(params: GetAccommodationsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getAccommodations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAccommodationsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccommodations>>> = ({ signal }) => getAccommodations(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getAccommodations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetAccommodationsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getAccommodations>>>
export type GetAccommodationsSuspenseQueryError = ErrorType<GetAccommodations403>


export function useGetAccommodationsSuspense<TData = Awaited<ReturnType<typeof getAccommodations>>, TError = ErrorType<GetAccommodations403>>(
 params: GetAccommodationsParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getAccommodations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAccommodationsSuspense<TData = Awaited<ReturnType<typeof getAccommodations>>, TError = ErrorType<GetAccommodations403>>(
 params: GetAccommodationsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getAccommodations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetAccommodationsSuspense<TData = Awaited<ReturnType<typeof getAccommodations>>, TError = ErrorType<GetAccommodations403>>(
 params: GetAccommodationsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getAccommodations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary ログイン中のユーザーに紐づく全ての予約した宿泊施設の取得(ページネーションもあり)
 */

export function useGetAccommodationsSuspense<TData = Awaited<ReturnType<typeof getAccommodations>>, TError = ErrorType<GetAccommodations403>>(
 params: GetAccommodationsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getAccommodations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetAccommodationsSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



