/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query'
import type {
  DeleteTodoListsId200,
  DeleteTodoListsId403,
  DeleteTodoListsId500,
  GetTodoLists200,
  GetTodoLists403,
  GetTodoListsId200,
  GetTodoListsId403,
  GetTodoListsId404,
  GetTodoListsParams,
  PatchTodoListsId200,
  PatchTodoListsId403,
  PatchTodoListsId500,
  PatchTodoListsIdBody
} from '../../model'
import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType, BodyType } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * @summary ログイン中のユーザーに紐づく全てのTODOリストの取得(ページネーションもあり)
 */
export const getTodoLists = (
    params: GetTodoListsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetTodoLists200>(
      {url: `/api/todo-lists`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetTodoListsQueryKey = (params: GetTodoListsParams,) => {
    return [`/api/todo-lists`, ...(params ? [params]: [])] as const;
    }

    
export const getGetTodoListsQueryOptions = <TData = Awaited<ReturnType<typeof getTodoLists>>, TError = ErrorType<GetTodoLists403>>(params: GetTodoListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoLists>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTodoListsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodoLists>>> = ({ signal }) => getTodoLists(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTodoLists>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetTodoListsQueryResult = NonNullable<Awaited<ReturnType<typeof getTodoLists>>>
export type GetTodoListsQueryError = ErrorType<GetTodoLists403>


export function useGetTodoLists<TData = Awaited<ReturnType<typeof getTodoLists>>, TError = ErrorType<GetTodoLists403>>(
 params: GetTodoListsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoLists>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodoLists>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTodoLists<TData = Awaited<ReturnType<typeof getTodoLists>>, TError = ErrorType<GetTodoLists403>>(
 params: GetTodoListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoLists>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodoLists>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTodoLists<TData = Awaited<ReturnType<typeof getTodoLists>>, TError = ErrorType<GetTodoLists403>>(
 params: GetTodoListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoLists>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary ログイン中のユーザーに紐づく全てのTODOリストの取得(ページネーションもあり)
 */

export function useGetTodoLists<TData = Awaited<ReturnType<typeof getTodoLists>>, TError = ErrorType<GetTodoLists403>>(
 params: GetTodoListsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoLists>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetTodoListsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetTodoListsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getTodoLists>>, TError = ErrorType<GetTodoLists403>>(params: GetTodoListsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoLists>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTodoListsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodoLists>>> = ({ signal }) => getTodoLists(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoLists>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetTodoListsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getTodoLists>>>
export type GetTodoListsSuspenseQueryError = ErrorType<GetTodoLists403>


export function useGetTodoListsSuspense<TData = Awaited<ReturnType<typeof getTodoLists>>, TError = ErrorType<GetTodoLists403>>(
 params: GetTodoListsParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoLists>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTodoListsSuspense<TData = Awaited<ReturnType<typeof getTodoLists>>, TError = ErrorType<GetTodoLists403>>(
 params: GetTodoListsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoLists>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTodoListsSuspense<TData = Awaited<ReturnType<typeof getTodoLists>>, TError = ErrorType<GetTodoLists403>>(
 params: GetTodoListsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoLists>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary ログイン中のユーザーに紐づく全てのTODOリストの取得(ページネーションもあり)
 */

export function useGetTodoListsSuspense<TData = Awaited<ReturnType<typeof getTodoLists>>, TError = ErrorType<GetTodoLists403>>(
 params: GetTodoListsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoLists>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetTodoListsSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary 単一のTODOリストの取得
 */
export const getTodoListsId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetTodoListsId200>(
      {url: `/api/todo-lists/${id}`, method: 'GET', signal
    },
      options);
    }
  

export const getGetTodoListsIdQueryKey = (id: number,) => {
    return [`/api/todo-lists/${id}`] as const;
    }

    
export const getGetTodoListsIdQueryOptions = <TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId403 | GetTodoListsId404>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTodoListsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodoListsId>>> = ({ signal }) => getTodoListsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetTodoListsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTodoListsId>>>
export type GetTodoListsIdQueryError = ErrorType<GetTodoListsId403 | GetTodoListsId404>


export function useGetTodoListsId<TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId403 | GetTodoListsId404>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodoListsId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTodoListsId<TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId403 | GetTodoListsId404>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodoListsId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTodoListsId<TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId403 | GetTodoListsId404>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary 単一のTODOリストの取得
 */

export function useGetTodoListsId<TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId403 | GetTodoListsId404>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetTodoListsIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetTodoListsIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId403 | GetTodoListsId404>>(id: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTodoListsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodoListsId>>> = ({ signal }) => getTodoListsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetTodoListsIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getTodoListsId>>>
export type GetTodoListsIdSuspenseQueryError = ErrorType<GetTodoListsId403 | GetTodoListsId404>


export function useGetTodoListsIdSuspense<TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId403 | GetTodoListsId404>>(
 id: number, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTodoListsIdSuspense<TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId403 | GetTodoListsId404>>(
 id: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTodoListsIdSuspense<TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId403 | GetTodoListsId404>>(
 id: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary 単一のTODOリストの取得
 */

export function useGetTodoListsIdSuspense<TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId403 | GetTodoListsId404>>(
 id: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetTodoListsIdSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary TODOリスト更新API
 */
export const patchTodoListsId = (
    id: number,
    patchTodoListsIdBody: BodyType<PatchTodoListsIdBody>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<PatchTodoListsId200>(
      {url: `/api/todo-lists/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchTodoListsIdBody
    },
      options);
    }
  


export const getPatchTodoListsIdMutationOptions = <TError = ErrorType<PatchTodoListsId403 | PatchTodoListsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchTodoListsId>>, TError,{id: number;data: BodyType<PatchTodoListsIdBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchTodoListsId>>, TError,{id: number;data: BodyType<PatchTodoListsIdBody>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchTodoListsId>>, {id: number;data: BodyType<PatchTodoListsIdBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  patchTodoListsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchTodoListsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchTodoListsId>>>
    export type PatchTodoListsIdMutationBody = BodyType<PatchTodoListsIdBody>
    export type PatchTodoListsIdMutationError = ErrorType<PatchTodoListsId403 | PatchTodoListsId500>

    /**
 * @summary TODOリスト更新API
 */
export const usePatchTodoListsId = <TError = ErrorType<PatchTodoListsId403 | PatchTodoListsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchTodoListsId>>, TError,{id: number;data: BodyType<PatchTodoListsIdBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof patchTodoListsId>>,
        TError,
        {id: number;data: BodyType<PatchTodoListsIdBody>},
        TContext
      > => {

      const mutationOptions = getPatchTodoListsIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary TODOリスト削除API
 */
export const deleteTodoListsId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DeleteTodoListsId200>(
      {url: `/api/todo-lists/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteTodoListsIdMutationOptions = <TError = ErrorType<DeleteTodoListsId403 | DeleteTodoListsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTodoListsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTodoListsId>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTodoListsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteTodoListsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTodoListsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTodoListsId>>>
    
    export type DeleteTodoListsIdMutationError = ErrorType<DeleteTodoListsId403 | DeleteTodoListsId500>

    /**
 * @summary TODOリスト削除API
 */
export const useDeleteTodoListsId = <TError = ErrorType<DeleteTodoListsId403 | DeleteTodoListsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTodoListsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof deleteTodoListsId>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteTodoListsIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    