/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query'
import type {
  GetTodoListsId200,
  GetTodoListsId404
} from '../../model'
import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * @summary 単一のTODOリストの取得
 */
export const getTodoListsId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetTodoListsId200>(
      {url: `/api/todo-lists/${id}`, method: 'GET', signal
    },
      options);
    }
  

export const getGetTodoListsIdQueryKey = (id: number,) => {
    return [`/api/todo-lists/${id}`] as const;
    }

    
export const getGetTodoListsIdQueryOptions = <TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId404>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTodoListsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodoListsId>>> = ({ signal }) => getTodoListsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetTodoListsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTodoListsId>>>
export type GetTodoListsIdQueryError = ErrorType<GetTodoListsId404>


export function useGetTodoListsId<TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId404>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodoListsId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTodoListsId<TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId404>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodoListsId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTodoListsId<TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId404>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary 単一のTODOリストの取得
 */

export function useGetTodoListsId<TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId404>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetTodoListsIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetTodoListsIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId404>>(id: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTodoListsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodoListsId>>> = ({ signal }) => getTodoListsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetTodoListsIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getTodoListsId>>>
export type GetTodoListsIdSuspenseQueryError = ErrorType<GetTodoListsId404>


export function useGetTodoListsIdSuspense<TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId404>>(
 id: number, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTodoListsIdSuspense<TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId404>>(
 id: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTodoListsIdSuspense<TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId404>>(
 id: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary 単一のTODOリストの取得
 */

export function useGetTodoListsIdSuspense<TData = Awaited<ReturnType<typeof getTodoListsId>>, TError = ErrorType<GetTodoListsId404>>(
 id: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTodoListsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetTodoListsIdSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



