/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  GetTodoListsId200
} from '../../model'

export const getGetTodoListsIdResponseMock = (overrideResponse: Partial< GetTodoListsId200 > = {}): GetTodoListsId200 => ({id: faker.number.int({min: undefined, max: undefined}), items: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({dueDate: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), id: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), null]), isCompleted: faker.datatype.boolean(), order: faker.number.int({min: undefined, max: undefined}), title: faker.string.alpha(20)})), title: faker.string.alpha(20), tripDate: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), tripId: faker.number.int({min: undefined, max: undefined}), tripTitle: faker.string.alpha(20), ...overrideResponse})


export const getGetTodoListsIdMockHandler = (overrideResponse?: GetTodoListsId200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetTodoListsId200> | GetTodoListsId200)) => {
  return http.get('*/todo-lists/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetTodoListsIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getTodoListsMock = () => [
  getGetTodoListsIdMockHandler()
]
