/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query'
import type {
  DeleteTripsId200,
  DeleteTripsId403,
  DeleteTripsId500,
  GetTrips200,
  GetTrips403,
  GetTripsId200,
  GetTripsId403,
  GetTripsId404,
  GetTripsParams,
  PostTrips200,
  PostTrips403,
  PostTrips500,
  PostTripsBody
} from '../../model'
import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType, BodyType } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * @summary ログイン中のユーザーに紐づく全ての旅行情報の取得
 */
export const getTrips = (
    params: GetTripsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetTrips200>(
      {url: `/api/trips`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetTripsQueryKey = (params: GetTripsParams,) => {
    return [`/api/trips`, ...(params ? [params]: [])] as const;
    }

    
export const getGetTripsQueryOptions = <TData = Awaited<ReturnType<typeof getTrips>>, TError = ErrorType<GetTrips403>>(params: GetTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTripsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTrips>>> = ({ signal }) => getTrips(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTrips>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetTripsQueryResult = NonNullable<Awaited<ReturnType<typeof getTrips>>>
export type GetTripsQueryError = ErrorType<GetTrips403>


export function useGetTrips<TData = Awaited<ReturnType<typeof getTrips>>, TError = ErrorType<GetTrips403>>(
 params: GetTripsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrips>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrips>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTrips<TData = Awaited<ReturnType<typeof getTrips>>, TError = ErrorType<GetTrips403>>(
 params: GetTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrips>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrips>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTrips<TData = Awaited<ReturnType<typeof getTrips>>, TError = ErrorType<GetTrips403>>(
 params: GetTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary ログイン中のユーザーに紐づく全ての旅行情報の取得
 */

export function useGetTrips<TData = Awaited<ReturnType<typeof getTrips>>, TError = ErrorType<GetTrips403>>(
 params: GetTripsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetTripsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetTripsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getTrips>>, TError = ErrorType<GetTrips403>>(params: GetTripsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTripsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTrips>>> = ({ signal }) => getTrips(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTrips>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetTripsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getTrips>>>
export type GetTripsSuspenseQueryError = ErrorType<GetTrips403>


export function useGetTripsSuspense<TData = Awaited<ReturnType<typeof getTrips>>, TError = ErrorType<GetTrips403>>(
 params: GetTripsParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTripsSuspense<TData = Awaited<ReturnType<typeof getTrips>>, TError = ErrorType<GetTrips403>>(
 params: GetTripsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTripsSuspense<TData = Awaited<ReturnType<typeof getTrips>>, TError = ErrorType<GetTrips403>>(
 params: GetTripsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary ログイン中のユーザーに紐づく全ての旅行情報の取得
 */

export function useGetTripsSuspense<TData = Awaited<ReturnType<typeof getTrips>>, TError = ErrorType<GetTrips403>>(
 params: GetTripsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTrips>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetTripsSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary 旅程情報新規作成API
 */
export const postTrips = (
    postTripsBody: BodyType<PostTripsBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostTrips200>(
      {url: `/api/trips`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postTripsBody, signal
    },
      options);
    }
  


export const getPostTripsMutationOptions = <TError = ErrorType<PostTrips403 | PostTrips500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTrips>>, TError,{data: BodyType<PostTripsBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postTrips>>, TError,{data: BodyType<PostTripsBody>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postTrips>>, {data: BodyType<PostTripsBody>}> = (props) => {
          const {data} = props ?? {};

          return  postTrips(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostTripsMutationResult = NonNullable<Awaited<ReturnType<typeof postTrips>>>
    export type PostTripsMutationBody = BodyType<PostTripsBody>
    export type PostTripsMutationError = ErrorType<PostTrips403 | PostTrips500>

    /**
 * @summary 旅程情報新規作成API
 */
export const usePostTrips = <TError = ErrorType<PostTrips403 | PostTrips500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTrips>>, TError,{data: BodyType<PostTripsBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof postTrips>>,
        TError,
        {data: BodyType<PostTripsBody>},
        TContext
      > => {

      const mutationOptions = getPostTripsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary 単一の旅行情報の取得
 */
export const getTripsId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetTripsId200>(
      {url: `/api/trips/${id}`, method: 'GET', signal
    },
      options);
    }
  

export const getGetTripsIdQueryKey = (id: number,) => {
    return [`/api/trips/${id}`] as const;
    }

    
export const getGetTripsIdQueryOptions = <TData = Awaited<ReturnType<typeof getTripsId>>, TError = ErrorType<GetTripsId403 | GetTripsId404>>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTripsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTripsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTripsId>>> = ({ signal }) => getTripsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTripsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetTripsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTripsId>>>
export type GetTripsIdQueryError = ErrorType<GetTripsId403 | GetTripsId404>


export function useGetTripsId<TData = Awaited<ReturnType<typeof getTripsId>>, TError = ErrorType<GetTripsId403 | GetTripsId404>>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTripsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTripsId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTripsId<TData = Awaited<ReturnType<typeof getTripsId>>, TError = ErrorType<GetTripsId403 | GetTripsId404>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTripsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTripsId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTripsId<TData = Awaited<ReturnType<typeof getTripsId>>, TError = ErrorType<GetTripsId403 | GetTripsId404>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTripsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary 単一の旅行情報の取得
 */

export function useGetTripsId<TData = Awaited<ReturnType<typeof getTripsId>>, TError = ErrorType<GetTripsId403 | GetTripsId404>>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTripsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetTripsIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetTripsIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getTripsId>>, TError = ErrorType<GetTripsId403 | GetTripsId404>>(id: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTripsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTripsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTripsId>>> = ({ signal }) => getTripsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTripsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetTripsIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getTripsId>>>
export type GetTripsIdSuspenseQueryError = ErrorType<GetTripsId403 | GetTripsId404>


export function useGetTripsIdSuspense<TData = Awaited<ReturnType<typeof getTripsId>>, TError = ErrorType<GetTripsId403 | GetTripsId404>>(
 id: number, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTripsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTripsIdSuspense<TData = Awaited<ReturnType<typeof getTripsId>>, TError = ErrorType<GetTripsId403 | GetTripsId404>>(
 id: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTripsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTripsIdSuspense<TData = Awaited<ReturnType<typeof getTripsId>>, TError = ErrorType<GetTripsId403 | GetTripsId404>>(
 id: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTripsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary 単一の旅行情報の取得
 */

export function useGetTripsIdSuspense<TData = Awaited<ReturnType<typeof getTripsId>>, TError = ErrorType<GetTripsId403 | GetTripsId404>>(
 id: number, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getTripsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetTripsIdSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary 旅程情報削除API
 */
export const deleteTripsId = (
    id: number,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DeleteTripsId200>(
      {url: `/api/trips/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteTripsIdMutationOptions = <TError = ErrorType<DeleteTripsId403 | DeleteTripsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTripsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTripsId>>, TError,{id: number}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTripsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteTripsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTripsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTripsId>>>
    
    export type DeleteTripsIdMutationError = ErrorType<DeleteTripsId403 | DeleteTripsId500>

    /**
 * @summary 旅程情報削除API
 */
export const useDeleteTripsId = <TError = ErrorType<DeleteTripsId403 | DeleteTripsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTripsId>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof deleteTripsId>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getDeleteTripsIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    