/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  DeleteTripsId200,
  GetTrips200,
  GetTripsId200,
  PostTrips200
} from '../../model'

export const getGetTripsResponseMock = (overrideResponse: Partial< GetTrips200 > = {}): GetTrips200 => ({totalPages: faker.number.int({min: undefined, max: undefined}), trips: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({destination: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), endDate: faker.string.alpha(20), id: faker.number.int({min: undefined, max: undefined}), image: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), startDate: faker.string.alpha(20), title: faker.string.alpha(20)})), ...overrideResponse})

export const getPostTripsResponseMock = (overrideResponse: Partial< PostTrips200 > = {}): PostTrips200 => ({id: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getGetTripsIdResponseMock = (overrideResponse: Partial< GetTripsId200 > = {}): GetTripsId200 => ({trip: {accommodationIds: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.int({min: undefined, max: undefined}))), undefined]), destination: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), endDate: faker.string.alpha(20), id: faker.number.int({min: undefined, max: undefined}), image: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), startDate: faker.string.alpha(20), title: faker.string.alpha(20), todoIds: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.int({min: undefined, max: undefined}))), undefined]), tripDays: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({dayDate: faker.string.alpha(20), dayDescription: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), dayOrder: faker.number.int({min: undefined, max: undefined}), tripDayId: faker.number.int({min: undefined, max: undefined}), tripRoutePoints: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({accommodationId: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}), undefined]), address: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), arrivalTime: faker.string.alpha(20), departureTime: faker.string.alpha(20), id: faker.number.int({min: undefined, max: undefined}), imageUrl: faker.helpers.arrayElement([faker.string.alpha(20), undefined]), latLng: faker.helpers.arrayElement([{x: faker.number.int({min: undefined, max: undefined}), y: faker.number.int({min: undefined, max: undefined})}, undefined]), name: faker.string.alpha(20), visitOrder: faker.number.int({min: undefined, max: undefined})})), undefined])}))}, ...overrideResponse})

export const getDeleteTripsIdResponseMock = (overrideResponse: Partial< DeleteTripsId200 > = {}): DeleteTripsId200 => ({id: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})


export const getGetTripsMockHandler = (overrideResponse?: GetTrips200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetTrips200> | GetTrips200)) => {
  return http.get('*/trips', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetTripsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getPostTripsMockHandler = (overrideResponse?: PostTrips200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostTrips200> | PostTrips200)) => {
  return http.post('*/trips', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getPostTripsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetTripsIdMockHandler = (overrideResponse?: GetTripsId200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetTripsId200> | GetTripsId200)) => {
  return http.get('*/trips/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetTripsIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getDeleteTripsIdMockHandler = (overrideResponse?: DeleteTripsId200 | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeleteTripsId200> | DeleteTripsId200)) => {
  return http.delete('*/trips/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getDeleteTripsIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getTripsMock = () => [
  getGetTripsMockHandler(),
  getPostTripsMockHandler(),
  getGetTripsIdMockHandler(),
  getDeleteTripsIdMockHandler()
]
