/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'
import type {
  PatchTripRoutePointsReorder200,
  PatchTripRoutePointsReorder400,
  PatchTripRoutePointsReorder403,
  PatchTripRoutePointsReorder404,
  PatchTripRoutePointsReorder500,
  PatchTripRoutePointsReorderBody,
  PostTripRoutePoints200,
  PostTripRoutePoints403,
  PostTripRoutePoints500,
  PostTripRoutePointsBody
} from '../../model'
import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType, BodyType } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * @summary 目的地新規作成API
 */
export const postTripRoutePoints = (
    postTripRoutePointsBody: BodyType<PostTripRoutePointsBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostTripRoutePoints200>(
      {url: `/api/trip-route-points`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postTripRoutePointsBody, signal
    },
      options);
    }
  


export const getPostTripRoutePointsMutationOptions = <TError = ErrorType<PostTripRoutePoints403 | PostTripRoutePoints500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTripRoutePoints>>, TError,{data: BodyType<PostTripRoutePointsBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postTripRoutePoints>>, TError,{data: BodyType<PostTripRoutePointsBody>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postTripRoutePoints>>, {data: BodyType<PostTripRoutePointsBody>}> = (props) => {
          const {data} = props ?? {};

          return  postTripRoutePoints(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostTripRoutePointsMutationResult = NonNullable<Awaited<ReturnType<typeof postTripRoutePoints>>>
    export type PostTripRoutePointsMutationBody = BodyType<PostTripRoutePointsBody>
    export type PostTripRoutePointsMutationError = ErrorType<PostTripRoutePoints403 | PostTripRoutePoints500>

    /**
 * @summary 目的地新規作成API
 */
export const usePostTripRoutePoints = <TError = ErrorType<PostTripRoutePoints403 | PostTripRoutePoints500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTripRoutePoints>>, TError,{data: BodyType<PostTripRoutePointsBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof postTripRoutePoints>>,
        TError,
        {data: BodyType<PostTripRoutePointsBody>},
        TContext
      > => {

      const mutationOptions = getPostTripRoutePointsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary 目的地の訪問順序・時間の一括更新API
 */
export const patchTripRoutePointsReorder = (
    patchTripRoutePointsReorderBody: BodyType<PatchTripRoutePointsReorderBody>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<PatchTripRoutePointsReorder200>(
      {url: `/api/trip-route-points/reorder`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: patchTripRoutePointsReorderBody
    },
      options);
    }
  


export const getPatchTripRoutePointsReorderMutationOptions = <TError = ErrorType<PatchTripRoutePointsReorder400 | PatchTripRoutePointsReorder403 | PatchTripRoutePointsReorder404 | PatchTripRoutePointsReorder500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchTripRoutePointsReorder>>, TError,{data: BodyType<PatchTripRoutePointsReorderBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchTripRoutePointsReorder>>, TError,{data: BodyType<PatchTripRoutePointsReorderBody>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchTripRoutePointsReorder>>, {data: BodyType<PatchTripRoutePointsReorderBody>}> = (props) => {
          const {data} = props ?? {};

          return  patchTripRoutePointsReorder(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchTripRoutePointsReorderMutationResult = NonNullable<Awaited<ReturnType<typeof patchTripRoutePointsReorder>>>
    export type PatchTripRoutePointsReorderMutationBody = BodyType<PatchTripRoutePointsReorderBody>
    export type PatchTripRoutePointsReorderMutationError = ErrorType<PatchTripRoutePointsReorder400 | PatchTripRoutePointsReorder403 | PatchTripRoutePointsReorder404 | PatchTripRoutePointsReorder500>

    /**
 * @summary 目的地の訪問順序・時間の一括更新API
 */
export const usePatchTripRoutePointsReorder = <TError = ErrorType<PatchTripRoutePointsReorder400 | PatchTripRoutePointsReorder403 | PatchTripRoutePointsReorder404 | PatchTripRoutePointsReorder500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchTripRoutePointsReorder>>, TError,{data: BodyType<PatchTripRoutePointsReorderBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof patchTripRoutePointsReorder>>,
        TError,
        {data: BodyType<PatchTripRoutePointsReorderBody>},
        TContext
      > => {

      const mutationOptions = getPatchTripRoutePointsReorderMutationOptions(options);

      return useMutation(mutationOptions);
    }
    