/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */

export type GetAccommodations200AccommodationsItem = {
  address?: string;
  bookingId?: string;
  bookingUrl?: string;
  checkIn: string;
  checkOut: string;
  id: number;
  image: string;
  name: string;
};
