/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import type { GetAccommodationsId200Accommodation } from './getAccommodationsId200Accommodation';

export type GetAccommodationsId200 = {
  accommodation: GetAccommodationsId200Accommodation;
};
