/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */

export type GetAccommodationsId200Accommodation = {
  address?: string;
  bookingId?: string;
  bookingUrl?: string;
  checkIn: string;
  checkOut: string;
  id: number;
  image?: string;
  informationUrl?: string;
  name: string;
  notes?: string;
  phoneNumber?: string;
  reservationPrice?: number;
  tripId?: number;
};
