/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import type { GetAccommodations200AccommodationsItem } from './getAccommodations200AccommodationsItem';

export type GetAccommodations200 = {
  accommodations: GetAccommodations200AccommodationsItem[];
  totalPages: number;
};
