/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import type { GetAccommodationsSearch200AccommodationsItem } from './getAccommodationsSearch200AccommodationsItem';

export type GetAccommodationsSearch200 = {
  accommodations: GetAccommodationsSearch200AccommodationsItem[];
};
