/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */

export type GetAccommodationsSearch200AccommodationsItem = {
  address: string;
  hotelImageUrl: string;
  id: number;
  informationUrl: string;
  name: string;
  phoneNumber: string;
  reviewAverage: number;
  reviewCount: number;
};
