/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */

export type GetTodoListsId200ItemsItem = {
  dueDate?: string;
  id: number;
  isCompleted: boolean;
  order: number;
  title: string;
};
