/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import type { GetTripsId200TripTripDaysItemTripRoutePointsItemLatLng } from './getTripsId200TripTripDaysItemTripRoutePointsItemLatLng';

export type GetTripsId200TripTripDaysItemTripRoutePointsItem = {
  address?: string;
  arrivalTime: string;
  departureTime: string;
  imageUrl?: string;
  latLng?: GetTripsId200TripTripDaysItemTripRoutePointsItemLatLng;
  name: string;
  visitOrder: number;
};
