/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import type { GetTrips200TripsItem } from './getTrips200TripsItem';

export type GetTrips200 = {
  totalPages: number;
  trips: GetTrips200TripsItem[];
};
