/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import type { GetTodoListsId200ItemsItem } from './getTodoListsId200ItemsItem';

export type GetTodoListsId200 = {
  id: number;
  items: GetTodoListsId200ItemsItem[];
  title: string;
  tripDate?: string;
  tripId: number;
  tripTitle: string;
};
