/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */

export type GetTodoLists200TodoListsItem = {
  completedTasks: number;
  id: number;
  startDate?: string;
  title: string;
  totalTasks: number;
};
