/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import type { GetTripsId200TripTripDaysItem } from './getTripsId200TripTripDaysItem';

export type GetTripsId200Trip = {
  accommodationIds: number[];
  destination?: string;
  endDate: string;
  id: number;
  image?: string;
  startDate: string;
  title: string;
  todoIds: number[];
  tripDays: GetTripsId200TripTripDaysItem[];
};
