/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import type { GetTodoLists200TodoListsItem } from './getTodoLists200TodoListsItem';

export type GetTodoLists200 = {
  todoLists: GetTodoLists200TodoListsItem[];
  totalPages: number;
};
