/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import type { PatchTripRoutePointsIdBodyTripRoutePoint } from './patchTripRoutePointsIdBodyTripRoutePoint';

export type PatchTripRoutePointsIdBody = {
  tripRoutePoint: PatchTripRoutePointsIdBodyTripRoutePoint;
};
