/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import type { PatchTripRoutePointsIdBodyTripRoutePointAccommodation } from './patchTripRoutePointsIdBodyTripRoutePointAccommodation';
import type { PatchTripRoutePointsIdBodyTripRoutePointDestination } from './patchTripRoutePointsIdBodyTripRoutePointDestination';

export type PatchTripRoutePointsIdBodyTripRoutePoint = {
  accommodation?: PatchTripRoutePointsIdBodyTripRoutePointAccommodation;
  destination?: PatchTripRoutePointsIdBodyTripRoutePointDestination;
};
