/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import type { PostTripRoutePointsBodyTripRoutePointAccommodation } from './postTripRoutePointsBodyTripRoutePointAccommodation';
import type { PostTripRoutePointsBodyTripRoutePointDestination } from './postTripRoutePointsBodyTripRoutePointDestination';

export type PostTripRoutePointsBodyTripRoutePoint = {
  accommodation?: PostTripRoutePointsBodyTripRoutePointAccommodation;
  destination?: PostTripRoutePointsBodyTripRoutePointDestination;
};
