/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import type { PostTripRoutePointsBodyTripRoutePointAccommodationLatLng } from './postTripRoutePointsBodyTripRoutePointAccommodationLatLng';

export type PostTripRoutePointsBodyTripRoutePointAccommodation = {
  accommodationId?: number;
  address?: string;
  arrivalTime: string;
  departureTime: string;
  imageUrl?: string;
  latLng?: PostTripRoutePointsBodyTripRoutePointAccommodationLatLng;
  name?: string;
  tripDayId: number;
};
