/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import type { PostRegister200User } from './postRegister200User';

export type PostRegister200 = {
  user: PostRegister200User;
};
