/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import type { PostTripRoutePointsBodyTripRoutePointDestinationLatLng } from './postTripRoutePointsBodyTripRoutePointDestinationLatLng';

export type PostTripRoutePointsBodyTripRoutePointDestination = {
  address: string;
  arrivalTime: string;
  departureTime: string;
  imageUrl?: string;
  latLng?: PostTripRoutePointsBodyTripRoutePointDestinationLatLng;
  name: string;
  tripDayId: number;
};
