/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import type { PostVerifyEmail200User } from './postVerifyEmail200User';

export type PostVerifyEmail200 = {
  user: PostVerifyEmail200User;
};
