/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import type { PostTripRoutePointsBodyTripRoutePointLatLng } from './postTripRoutePointsBodyTripRoutePointLatLng';

export type PostTripRoutePointsBodyTripRoutePoint = {
  address: string;
  arrivalTime: string;
  departureTime: string;
  latLng?: PostTripRoutePointsBodyTripRoutePointLatLng;
  name: string;
  tripDayId: number;
};
