openapi: 3.1.0
info:
  title: tripeasy
  version: 1.0.0
  description: TripeasyのAPI仕様書
components:
  schemas: {}
  parameters: {}
paths:
  /register:
    post:
      summary: 新規ユーザー登録API
      tags:
        - register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - name
                - email
                - password
      responses:
        "200":
          description: 新規ユーザー登録成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                        nullable: true
                    required:
                      - id
                      - name
                required:
                  - user
        "409":
          description: 登録済みのメールアドレスにつき登録失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
  /verify-email:
    post:
      summary: メール検証API
      tags:
        - verify-email
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
              required:
                - token
      responses:
        "200":
          description: メール検証成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      email:
                        type: string
                        nullable: true
                    required:
                      - email
                required:
                  - user
        "400":
          description: 有効なトークンでないので検証失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "404":
          description: 対象のリソースが見つからないので検証失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
  /request-token:
    post:
      summary: トークンの再発行API
      tags:
        - request-token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      responses:
        "200":
          description: トークンの発行成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "400":
          description: メールアドレスがすでに認証済みのため失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "404":
          description: メールアドレスが未登録のため失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
        "500":
          description: トークンの生成に失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
  /todo-items:
    post:
      summary: TODOアイテム新規作成API
      tags:
        - todo-items
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                todoListId:
                  type: number
                todoItem:
                  type: object
                  properties:
                    title:
                      type: string
                    dueDate:
                      type: string
                    isCompleted:
                      type: boolean
                    order:
                      type: number
                  required:
                    - title
                    - isCompleted
                    - order
              required:
                - todoListId
                - todoItem
      responses:
        "200":
          description: TODOアイテム作成成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                required:
                  - id
        "500":
          description: TODOアイテム作成に失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
  /todo-items/{id}:
    patch:
      summary: TODOアイテム更新API
      tags:
        - todo-items
      parameters:
        - schema:
            type: number
          required: true
          name: id
          in: path
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                dueDate:
                  type: string
              required:
                - title
      responses:
        "200":
          description: TODOアイテム更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                required:
                  - id
        "500":
          description: TODOアイテム更新に失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
    delete:
      summary: TODOアイテム削除API
      tags:
        - todo-items
      parameters:
        - schema:
            type: number
          required: true
          name: id
          in: path
      responses:
        "200":
          description: TODOアイテム削除成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                required:
                  - id
        "500":
          description: TODOアイテム削除に失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
  /todo-items/is-completed/{id}:
    patch:
      summary: TODOアイテムのisCompletedの更新API
      tags:
        - todo-items
      parameters:
        - schema:
            type: number
          required: true
          name: id
          in: path
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                isCompleted:
                  type: boolean
              required:
                - isCompleted
      responses:
        "200":
          description: TODOアイテム更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                required:
                  - id
        "500":
          description: TODOアイテム更新に失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
  /todo-lists/{id}:
    get:
      summary: 単一のTODOリストの取得
      tags:
        - todo-lists
      parameters:
        - schema:
            type: number
          required: true
          name: id
          in: path
      responses:
        "200":
          description: TODOリスト取得成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                  tripId:
                    type: number
                  tripTitle:
                    type: string
                  tripDate:
                    type: string
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                          nullable: true
                        title:
                          type: string
                        dueDate:
                          type: string
                        isCompleted:
                          type: boolean
                        order:
                          type: number
                      required:
                        - id
                        - title
                        - isCompleted
                        - order
                required:
                  - id
                  - title
                  - tripId
                  - tripTitle
                  - items
        "404":
          description: TODOリストが存在しないので取得失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                  - message
