/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  PostTodoItems200
} from '../../model'

export const getPostTodoItemsResponseMock = (overrideResponse: Partial< PostTodoItems200 > = {}): PostTodoItems200 => ({id: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})


export const getPostTodoItemsMockHandler = (overrideResponse?: PostTodoItems200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<PostTodoItems200> | PostTodoItems200)) => {
  return http.post('*/todo-items', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getPostTodoItemsResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}
export const getTodoItemsMock = () => [
  getPostTodoItemsMockHandler()
]
