/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * tripeasy
 * TripeasyのAPI仕様書
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'
import type {
  PostTodoItems200,
  PostTodoItems500,
  PostTodoItemsBody
} from '../../model'
import { customInstance } from '../../mutator/custom-instance';
import type { ErrorType, BodyType } from '../../mutator/custom-instance';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * @summary TODOアイテム新規作成、更新API
 */
export const postTodoItems = (
    postTodoItemsBody: BodyType<PostTodoItemsBody>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<PostTodoItems200>(
      {url: `/api/todo-items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postTodoItemsBody, signal
    },
      options);
    }
  


export const getPostTodoItemsMutationOptions = <TError = ErrorType<PostTodoItems500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTodoItems>>, TError,{data: BodyType<PostTodoItemsBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postTodoItems>>, TError,{data: BodyType<PostTodoItemsBody>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postTodoItems>>, {data: BodyType<PostTodoItemsBody>}> = (props) => {
          const {data} = props ?? {};

          return  postTodoItems(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostTodoItemsMutationResult = NonNullable<Awaited<ReturnType<typeof postTodoItems>>>
    export type PostTodoItemsMutationBody = BodyType<PostTodoItemsBody>
    export type PostTodoItemsMutationError = ErrorType<PostTodoItems500>

    /**
 * @summary TODOアイテム新規作成、更新API
 */
export const usePostTodoItems = <TError = ErrorType<PostTodoItems500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTodoItems>>, TError,{data: BodyType<PostTodoItemsBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof postTodoItems>>,
        TError,
        {data: BodyType<PostTodoItemsBody>},
        TContext
      > => {

      const mutationOptions = getPostTodoItemsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    